# Generated by Django 4.1 on 2022-08-29 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="score",
            field=models.IntegerField(blank=True, default=150, null=True),
        ),
    ]
